services:
  - type: web
    name: orshimo-tours
    runtime: node
    buildCommand: npm ci --include=dev && npx vite build && npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist
    startCommand: NODE_ENV=production npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: SENDGRID_API_KEY
        sync: false
      - key: ADMIN_EMAIL
        value: david.alpenidze@gmail.com
      - key: FROM_EMAIL
        value: david.alpenidze@gmail.com
      - key: DEFAULT_OBJECT_STORAGE_BUCKET_ID
        sync: false
      - key: PRIVATE_OBJECT_DIR
        value: .private
      - key: PUBLIC_OBJECT_SEARCH_PATHS
        value: public
      - key: GOOGLE_PROJECT_ID
        sync: false
      - key: GOOGLE_CLIENT_EMAIL
        sync: false
      - key: GOOGLE_PRIVATE_KEY
        sync: false
